export const ARTICLE_LIST_REQUEST = "ARTICLE_LIST_REQUEST";
export const ARTICLE_LIST_SUCCESS = "ARTICLE_LIST_SUCCESS";
export const ARTICLE_LIST_FAIL = "ARTICLE_LIST_FAIL";

export const ARTICLE_SAVE_REQUEST = "ARTICLE_SAVE_REQUEST";
export const ARTICLE_SAVE_SUCCESS = "ARTICLE_SAVE_SUCCESS";
export const ARTICLE_SAVE_FAIL = "ARTICLE_SAVE_FAIL";

export const ARTICLE_DELETE_REQUEST = "ARTICLE_DELETE_REQUEST";
export const ARTICLE_DELETE_SUCCESS = "ARTICLE_DELETE_SUCCESS";
export const ARTICLE_DELETE_FAIL = "ARTICLE_DELETE_FAIL";
